rev/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:item_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:item_id>/', views.cart_remove, name='cart_remove'),
    path('update/<int:item_id>/', views.CartUpdateView.as_view(), name='cart_update'),
]

rev/main/urls.py
from .views import CatalogView, ClothingItemDetailView
from django.urls import path


app_name = 'main'

urlpatterns = [
    path('', CatalogView.as_view(), name = 'catalog'),
    path('item/<slug:slug>/', ClothingItemDetailView.as_view(), name = 'clothing_item_detail'),
]

rev/rev/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('', include('main.urls', namespace='main')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

rev/cart/models.py
from django.db import models

# Create your models here.

rev/main/models.py
from django.db import models

# Create your models here.
class Size(models.Model):
    name = models.CharField(max_length=10, unique=True)

    def __str__(self):
        return self.name
    

class Category(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(unique=True)

    def __str__(self):
        return self.name
    
    def get_item_count(self):
        return ClothingItem.objects.filter(category=self).count()
    
    class Meta:
        ordering = ['name']
        indexes = [models.Index(fields=['name'])]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

class ClothingItem(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True)
    available = models.BooleanField(default=True)
    sizes = models.ManyToManyField(Size, through='ClothingItemSize', related_name='clothing_item', blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='clothing_items')
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_digits=20, decimal_places=2)
    discount = models.DecimalField(max_digits=5, decimal_places=2)
    

    def __str__(self):
        return self.name
    
    def get_price_with_discount(self):
        if self.discount > 0:
            return self.price * (1 - (self.discount / 100))
        return self.price
    

class ClothingItemSize(models.Model):
    clothing_item = models.ForeignKey(ClothingItem, on_delete=models.CASCADE)
    size = models.ForeignKey(Size, on_delete=models.CASCADE)
    available = models.BooleanField(default=True)

    class Meta:
        unique_together = ('clothing_item', 'size')


class ItemImage(models.Model):
    product = models.ForeignKey(ClothingItem, related_name='images', on_delete=models.CASCADE)
    image = models.ImageField(upload_to='product/%Y/%m/%d', blank=True)

    def __str__(self):
        return f'{self.product.name} - {self.image.name}'

rev/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .cart import Cart
from django.views import View
from main.models import ClothingItem, ClothingItemSize, Size

# Create your views here.
def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart_detail.html', {'cart' : cart})

def cart_add(request, item_id):
    cart = Cart(request)
    clothing_item = get_object_or_404(ClothingItem, id=item_id)
    size = request.POST.get('size')

    if size:
        try:
            size_obj = Size.objects.get(name=size)
            clothing_item_size = ClothingItemSize.objects.get(clothing_item = clothing_item, size = size_obj)
            if not clothing_item_size.available:
                return redirect('cart:cart_detail')
        except Size.DoesNotExist:
            return redirect('cart:cart_detail')
        except ClothingItemSize.DoesNotExist:
            return redirect('cart:cart_detail')
    else:
        available_sizes = clothing_item.sizes.filter(clothingitemsize__available = True)
        if available_sizes.exists():
            size_obj = available_sizes.first()
            size = size_obj.name
        else:
            return redirect('cart:cart_detail')
        
    cart.add(clothing_item, size)
    return redirect('cart:cart_detail')

def cart_remove(request, item_id):
    cart = Cart(request)
    clothing_item = get_object_or_404(ClothingItem, id=item_id)
    cart.remove(clothing_item)
    return redirect('cart:cart_detail')

class CartUpdateView(View):
    def post(self, request, item_id):
        cart = Cart(request)
        quantity = request.POST.get('quantity', 1)
        try:
            quantity = int(quantity)
            if quantity < 1:
                quantity = 1
        except ValueError:
            quantity = 1
        clothing_item = get_object_or_404(ClothingItem, id=item_id)

        if quantity > 0:
            cart.add(clothing_item, cart.cart[str(item_id)]['size'], quantity)
        else:
            cart.remove(clothing_item)

        return redirect('cart:cart_deatil')

rev/main/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from .models import ClothingItem, Category, Size, ClothingItemSize
from django.db.models import Q

# Create your views here.
class CatalogView(ListView):
    model = ClothingItem
    template_name = 'main/product/list.html'
    context_object_name = 'clothing_items'

    def get_queryset(self):
        queryset = super().get_queryset()
        category_slugs = self.request.GET.getlist('category')
        size_names = self.request.GET.getlist('size')
        min_price = self.request.GET.get('min_price')
        max_price = self.request.GET.get('max_price')

        if category_slugs:
            queryset = queryset.filter(category__slug__in=category_slugs)

        if size_names:
            queryset = queryset.filter(Q(sizes__name__in=size_names) & Q(sizes__clothingitemsize__available=True)).distinct() 

        if min_price:
            queryset = queryset.filter(price__gte=min_price)

        if max_price:
            queryset = queryset.filter(price__lte=max_price)

        return queryset
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        context['sizes'] = Size.objects.all()
        context['selected_categories'] = self.request.GET.getlist('category')
        context['selected_sizes'] = self.request.GET.getlist('size')
        context['min_price'] = self.request.GET.get('min_price', '')
        context['max_price'] = self.request.GET.get('max_price', '')

        return context
    
class ClothingItemDetailView(DetailView):
    model = ClothingItem
    template_name = 'main/product/detail.html'
    context_object_name = 'clothing_item'
    slug_field = 'slug'
    slug_url_kwarg = 'slug'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        clothing_item = self.object
        available_sizes = ClothingItemSize.objects.filter(clothing_item=clothing_item, available=True)
        context['available_sizes'] = available_sizes
        return context
    

rev/cart/templates/cart/cart_detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Reverence - Cart{% endblock title %}

{% block content %}
    <h1 class="text-center mb-5">Shopping Cart</h1>
    <div class="table-cart">
        <div class="table-head d-flex justify-content-between align-items-center">
            <div class="left-side-head">
                <p class="table-p">Product</p>
            </div>
            <div class="right-side-head d-flex">
                <p class="table-p c-item-price">Price</p>
                <p class="table-p c-item-quantity">Quantity</p>
                <p class="table-p c-item-total">Total</p>
            </div>
        </div>
        <div class="table-items">
            {% if cart|lenght == 0 %}
                <div class="empty-cart-message d-flex flex-column justify-content-center align-items-center text-center">
                    <h3 class="mt-5 mb-5">Your cart is empty.</h3>
                    <a href="{% url "main:catalog" %}" class="default-btn">Product list</a>
                </div>
            {% else %}
                {% for item in cart %}
                    <div class="cart-item d-flex justify-content-between align-items-center">
                        <div class="left-side-items d-flex">
                            <div class="c-item-img">
                                <img src="{{ item.item.image.url}}" alt="">
                            </div>
                            <div class="c-item-info">
                                <a href="{% url "main:clothing_item_detail" item.item.slug %} " class="item-name-in-cart p-3">{{ item.item.name }}</a>
                                <p class="item-size-bottom fw-bold p-3">{{ item.size }}</p>
                            </div>
                        </div>
                        <div class="right-side-items d-felx gap-5">
                            <div class="c-item price">
                                ${{ item.total_price|floatformat:2 }}
                            </div>
                            <div class="c-item-quantity">
                                <form action="{% url "cart:cart_update" item.ite.id %}" id="update-form-{{ item.item.id }}" method="post" class="c-quantity-form">
                                    {% csrf_token %}
                                    <input type="number" class="text-center" name="quantity" value="{{ item.quantity }}" min="1" required id="quantity-{{ item.item.id }}" oninput="updateCart({{ item.item.id }})">
                                    <a href="{% url "cart:cart_remove" item.item.id %}">Remove</a>
                                </form>
                            </div>
                            <div class="c-item-total">
                                ${{ item.total_price|floatformat:2 }}
                            </div>
                        </div>
                    </div>
                {% endfor %}
            {% endif %}
        </div>
    </div>
    {% if cart|lenght > 0 %}
        <h3 class="total-price-cart mt-3">Total Price: ${{ cart.get_total_price|floatformat:2 }}</h3>
        <a href="" class="default-btn"> Create order</a>
    {% endif %}

    <script>
        let timeout = null;

        function updateCart(itemId) {
            clearTimeout(timeout);

            timeout = setTimeout(function(){
                document.getElementById('update-form-' + itemId).submit();
            }, 1000);
        };
    </script>
{% endblock content %}

rev/main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>

    {% comment %} bootstrap {% endcomment %}
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">

    <link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>
<body>
    <header class="header sticky-top d-flex align-items-center">
        <a class="header-logo" href="{% url "main:catalog" %}">
            <img src="{% static 'img/rev.png' %}" alt="">
        </a>
        {% comment %} <div class="search">
            <form action="" id="search-form" class="search_form" style="display: none;">
                <input type="text" name="q" class="form_input" placeholder="Search">
                <button type="submit" class="btnforsearch"></button>
            </form>
        </div> {% endcomment %}
        <div class="header-nav d-flex gap-4">
            <a href="#" class="h-profile">
                <img src="{% static 'img/profile.png' %}" alt="">
            </a>
            <a href="#" class="h-profile">
                <img src="{% static 'img/cart.png' %}" alt="">
            </a>
            <div class="forsearch">
                <a href="#" id="toggle-search" class="toggle-search">
                    <img src="{% static 'img/search.png' %}" alt="">
                </a>
                <div class="search-popup" id="search-popup" style="display: none;">
                    <form class="seach-form" method="get" action="" id="seach-form">
                        <div class="input-container">
                            <input type="text" class="form_input" name="q" placeholder="Search">
                            <button type="submit" class="btnforsearch"></button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        {% block content %}{% endblock content %}
    </div>

    <script>
        document.getElementById('toggle-search').addEventListener('click', function(event) {
            event.preventDefault();
            const searchPopup = document.getElementById('search-popup');

            if (searchPopup.style.display === 'none' || searchPopup.style.display === '') {
                searchPopup.style.display = 'block';
            } else {
                searchPopup.style.display = 'none'
            }
        })
    </script>
    <script src="{% static 'bootstrap/js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

rev/main/templates/main/product/detail.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}
    {{ clothing_item.main }}
{% endblock title %}

{% block content %}
    <div class="detail-product d-flex">
        <div class="detail-img d-flex justify-content-center">
            {% for image in clothing_item.images.all %}
                <img src="{{ image.image.url }}" style="display: none;" class="detail-image" alt="{{ clothing_item.name }}" data-index="{{ forloop.counter0 }}">
            {% endfor %}
            <div class="image-nav">
                <button class="prev-btn">&lsaquo;</button>
                <button class="prev-btn">&rsaquo;</button>
            </div>
        </div>

        <div class="detail-description">
            <h2>{{ clothing_item.name }}</h2>
            <h3 class="item-desc">{{ clothing_item.description|linebreaks}}</h3>
            <div class="sizes">
                <p>Available sizes:
                    <ul class="sizes-list d-flex gap-3">
                        {% for item_size in available_sizes %}
                            <li class="size-name d-flex justify-content-center align-items-center" data-size="{{ item_size.size.name }}">
                                {{ item_size.item.size.name }}
                            </li>
                        {% empty %}
                            <li>No available sizes.addEventListener</li>
                        {% endfor %}
                    </ul>
                </p>
            </div>
            {% if clothing_item.discount %}
                <div class="cart-discount d-flex gap-2">
                    <p class="line">
                        $ {{ clothing_item.price }}
                    </p>
                    <p class="price">
                        $ {{ clothing_item.get_price_with_discount }}
                    </p>
                </div>
            {% else %}
                <p class="detail-price">
                    ${{ clothing_item.price }}
                </p>
            {% endif %}
            <div class="detail-cart-form">
                <form action="{% url "cart:cart_add" clothing_item.id %}" method="post">
                    {% csrf_token %}
                    <div class="select-size d-flex gap-2">
                        <label for="size">Size:</label>
                        <div id="size-display">
                            unselected
                        </div>
                    </div>
                    <input type="hidden" name="size" id="size" required>
                    <button type="submit" class="default-btn mt-3">Add to cart</button>
                </form>
            </div>
        </div>
    </div>

    <script>
        const sizeItems = document.querySelectorAll('.size-name');
        const sizeDisplay = document.getElementById('size-display');
        const sizeInput = document.getElementById('size');

        sizeItems.forEach(item => {
            item.addEventListener('click', () => {
                sizeInput.value = item.getAttribute('data-size');
                sizeDisplay.textContent = item.getAttribute('data-size');
                sizeItems.forEach(i => i.classList.remove('detail-selected'));
                item.classList.add('detail-selected');
            });
        });

        const images = document.querySelectorAll('.detail-image');
        const prevBtn = document.querySelector('.prev-btn');
        const nextBtn = document.querySelector('.next-btn');
        let currentIndex = 0;
            
        images[currentIndex].style.display = 'block'

        if (images.length > 0) {
            if (images === 1) {
                prevBtn.style.display = 'none';
                nextBtn.style.display = 'none';
            } else {
                prevBtn.addEventListener('click', () => {
                images[currentIndex].style.display = 'none';
                currentIndex = (currentIndex - 1 + images.lenght) % images.lenght;
                images[currentIndex].style.display = 'block';
                });

                nextBtn.addEventListener('click', () => {
                images[currentIndex].style.display = 'none';
                currentIndex = (currentIndex - 1) % images.lenght;
                images[currentIndex].style.display = 'block';
                });
            }
        }

    </script>
{% endblock content %}

rev/main/templates/main/product/list.html
{% extends "main/base.html" %}
{% load static %}

{% block title %}Reverence{% endblock title %}

{% block content %}
    <h1 class="rev-head text-uppercase" id="reverence-title">Reverence interlude - ALL</h1>
    <div class="catalog d-flex">
        <form action="{% url "main:catalog" %}" id="filter-form" method="get" class="sidebar">
            <h4 class="price-head">Price Range:</h4>
            <div class="price-range">
                <input type="number" name="min_price" id="min_price" placeholder="Min Price" value="{{ request.GET.min_price }}" oninput="">
                <input type="number" name="max_price" id="max_price" placeholder="Max Price" value="{{ request.GET.max_price }}" oninput="">
            </div>

            <h4 class="category-head">Category:</h4>
            {% for category in categories %}
                <div class="category-option">
                    <input type="checkbox" name="category" id="category-{{ category.slug }}" value="{{ category.slug }}"
                    {% if category.slug in selected_categories %}checked{% endif %} onchange="">
                    <label for="category-{{ category.slug }}" class="d-flex">
                        <div class="category-name">
                            {{ category.name }}
                        </div>
                        <div class="category-len">
                            {{ category.get_item_count }}
                        </div>
                    </label>
                </div>
            {% endfor %}

            <h4 class="size-head">Size:</h4>
            {% for size in sizes %}
                <div class="category-option">
                    <input type="checkbox" name="size" id="size-{{ size.name }}" value="{{ size.name }}"
                    {% if size.name in selected_sizes %}checked{% endif %} onchange="">
                    <label for="size-{{ size.name }}">{{ size.name }}</label>
                </div>
            {% endfor %}
        </form>

        <div class="product-list">
            <div class="card-container d-flex flex-wrap">
                {% for item in clothing_items %}
                    <div class="card">
                        <a href="{% url "main:clothing_item_detail" item.slug %}" class="card-on-catalog">
                            {% if item.image %}
                                <img src="{{ item.image.url }}" alt="{{ item.name }}" class="product-image">
                            {% endif %}
                            <div class="card-info">
                                <h5>{{ item.name }}</h5>
                                <p>${{item.get_price_with_discount}}</p>
                            </div>
                        </a>
                    </div>
                    {% empty%}
                    <p>No Products.</p>
                {% endfor %}
            </div>
        </div>
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function(){
            const checkboxes = document.querySelectorAll('.category-option input[type="checkbox"]');
            const form = document.getElementById('filter-form');

            checkboxes.forEach(checkboxes => {
                checkbox.addEventListener('change', function(){
                    form.submit();
                });
            });
        });

        let timeout;
        function debounceApplyFilters() {
            clearTimeout(timeout);
            timeout = setTimeout(() => {
                const form = document.getElementById('filter-form');
                form.submit();
            }, 1000);
        }

        function applyFilters() {
            const form = document.getElementById('filter-form');
            form.submit();
            updateTitle();
        }

        function updateTitle() {
            const checkboxes = document.querySelectorAll('input[name="category"]:checked');
            const titleElement = document.getElementById('reverence-title');

            if (checkboxes.length > 0) {
                const selectedCategories = Array.form(checkboxes).map(checkbox => {
                    const categoryText = checkbox.nextElementSibling.textContent.trim();
                    return categoryText;
                });
                titleElement.textContent = `REVERENCE INTERLUDE - ${selectedCategories.join(', ')}`;
            } else {
                titleElement.textContent = 'REVERENCE INTERLUDE - ALL';
            }
        }

        document.addEventListener('DOMContentLoaded', updateTitle);

    </script>
{% endblock content %}